import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "About page",
  description: "Generated by create next app"
};

export default function About() {

  return (
    <div>
      О нас
    </div>
  );
}
