import Image from "next/image";
import styles from "./page.module.css";
import { Metadata } from 'next';
import { Button, Htag } from '@/components';

export const metadata: Metadata = {
  title: "Page title",
  description: "Generated by create next app"
};

export default function Home() {
  return (
    <>
      <Htag tag='h1'>TITLE</Htag>
      <Button appearance='primary'>Button</Button>
      <Button appearance='ghost'>Button</Button>
    </>
  );
}
